version: '3.8'

services:
  lmr2-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lmr2-cfr:latest
    container_name: lmr2-cfr-container

    # Mount volumes for data persistence
    volumes:
      # Mount local directories (adjust paths as needed)
      - ./data:/app/data
      - ./prev_data:/app/prev_data
      - ./cases:/app/cases
      - ./recons:/app/recons
      # Optional: mount scripts for development
      # - ./lmr_reproduce.py:/app/lmr_reproduce.py

    # Environment variables (if needed)
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=4
      - NUMEXPR_MAX_THREADS=4

    # Resource limits (optional - adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

    # Keep container running for interactive use
    stdin_open: true
    tty: true

    # Default command
    command: /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate cfr-env && exec bash"
